# Generated by Django 5.2.17 on 2026-08-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='about_education',
            field=models.TextField(blank=True, help_text='Your education and academic background.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_goal',
            field=models.TextField(blank=True, help_text='Your career goal and what type of opportunity you are looking for.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_intro',
            field=models.TextField(blank=True, help_text='Main introduction displayed at the top of the About section.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_what',
            field=models.TextField(blank=True, help_text='Information about what you do and your technical expertise.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_who',
            field=models.TextField(blank=True, help_text='Information about who you are.'),
        ),
    ]
