# Generated by Django 5.2.17 on 2026-08-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_siteprofile_about_education_siteprofile_about_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_education',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_goal',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_intro',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_what',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='about_who',
        ),
    ]
