# Generated by Django 5.2.17 on 2026-09-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcard',
            name='number',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume as a PDF file.', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
