# Generated by Django 5.2.17 on 2026-09-30 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_aboutcard_number_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools')], default='backend', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=80, help_text='0 se 100 ke beech', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skill',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('hackerrank', 'HackerRank'), ('github', 'GitHub'), ('other', 'Other')], default='other', max_length=30, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(help_text='Text shown on the site, e.g. LinkedIn', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Full profile link, starting with https://'),
        ),
    ]
