# Generated by Django 5.2.17 on 2026-10-01 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_skill_options_skill_category_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon CSS class, e.g. devicon-python-plain or fa-solid fa-key', max_length=60),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend Development'), ('api', 'API Development'), ('database', 'Database'), ('security', 'Security'), ('devops', 'DevOps & Server'), ('tools', 'Tools'), ('testing', 'Testing'), ('frontend', 'Frontend Integration')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=80, help_text='0 se 100 ke beech (ab design me use nahi hota)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
