# Generated by Django 5.2.17 on 2026-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill_icon_alter_skill_category_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='field',
            field=models.CharField(blank=True, help_text='e.g. Computer Science / IT (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='experience',
            name='kind',
            field=models.CharField(choices=[('experience', 'Experience'), ('education', 'Education')], default='experience', max_length=12),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, help_text='College / Company name (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. Python, Django, DRF, MySQL, JWT', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(help_text='e.g. 2023 - 2026 ya 2026 - Present', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text="e.g. Python Developer ya Bachelor's Degree", max_length=160),
        ),
    ]
